name = "un-data-worker"
main = "index.js"
# ⬇️ 添加下面这一行，日期填当天的
compatibility_date = "2026-06-27"

[[kv_namespaces]]
binding = "UN_DATA"
id = "59dca7d041bb464e85078458942a6a92"

[triggers]
crons = ["0 */6 * * *"]
